
- name: Copiar archivo de configuración Unattended Upgrades, omite dovecot
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
