---

- hosts: all
  become: true
  pre_tasks:

  - name: Descargar repo Ubuntu 20.04
    get_url:
     url: https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1+ubuntu20.04_all.deb
     dest: /home/rmartinez/
     mode: '0664'

  - name: Agrega repo a source list
    shell: dpkg -i /home/rmartinez/zabbix-release_5.2-1+ubuntu20.04_all.deb
    become: true
    become_method: sudo

  - name: Actualizar el índice de los repositorios (Ubuntu)
    tags: siempre
    apt:
     update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstations
  become: true
  roles:
    - workstations
