---

- hosts: all
  become: true
  pre_tasks:

  - name: Actualiza el índice de los repositorios (Ubuntu)
    tags: siempre
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Actualiza el índice de los repositorios (CentOS)
    tags: siempre
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"  

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstations
  become: true
  roles:
    - workstations
