---

- hosts: all
  become: true
  pre_tasks:

  - name: Actualizar el índice de los repositorios (Ubuntu)
    tags: siempre
    apt:
     update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: cyberpanel
  become: true
  roles:
    - cyberpanel

- hosts: web_servers_lemp
  become: true
  roles:
    - web_servers_lemp

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstations
  become: true
  roles:
    - workstations
