---

- hosts: cyberpanel
  become: true
  tasks:

  - name: Instalar Unattended Upgrades, Agente Zabbix, Net Tools
    apt:
      name:
        - unattended-upgrades
        - zabbix-agent
        - net-tools
      state: latest
      update_cache: yes
   #when: ansible_distribution in ["Debian", "Ubuntu"]
