- name: Crear usuario rmartinez
  user:
    name: rmartinez
    groups: root

- name: Agrega Llave SSH para rmartinez
  authorized_key:
    user: rmartinez
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMPBo3gKF98oTUGYeIe1XpmpkDOsXtBQAkb5166PzMOw tu mismo"

- name: Agrega archivo sudoers para rmartinez
  copy:
    src: sudoer_rmartinez
    dest: /etc/sudoers.d/rmartinez
    owner: root
    group: root
    mode: 0440

- name: Instalar Unattended Upgrades, Agente Zabbix2, Net Tools, Tmux
  apt:
   name:
    - unattended-upgrades
    - zabbix-agent2
    - net-tools
    - tmux
   state: latest
   update_cache: yes
  #when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Copiar archivo de configuración agente Zabbix
  copy:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644

- name: Inicia y habilita el agente Zabbix
  service:
    name: zabbix-agent2
    state: started
    enabled: yes

- name: Copiar archivo de configuración Unattended Upgrades, omite dovecot
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: Copiar archivo de configuración SSH
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Reinicia servicio SSH
  service:
    name: sshd
    state: restarted
