- name: Descargar repo Zabbix para Ubuntu 20.04
  get_url:
    url: https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1+ubuntu20.04_all.deb
    dest: /home/rmartinez/
    mode: '0664'

- name: Agrega repo Zabbix a source list
  shell: dpkg -i /home/rmartinez/zabbix-release_5.2-1+ubuntu20.04_all.deb
  become: true

- name: Crear usuario rmartinez
  user:
    name: rmartinez
    groups: root

- name: Agrega Llave SSH para rmartinez
  authorized_key:
    user: rmartinez
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMPBo3gKF98oTUGYeIe1XpmpkDOsXtBQAkb5166PzMOw tu mismo"

- name: Agrega Llave SSH para ansible
  authorized_key:
    user: rmartinez
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGNfMbCsEJP4Y4AoAQlldHiVQUlg3aCDpmIYZv8fNMUq ansible"

- name: Agrega archivo sudoers para rmartinez
  copy:
    src: sudoer_rmartinez
    dest: /etc/sudoers.d/rmartinez
    owner: root
    group: root
    mode: 0440

- name: Configurar zona horaria America/Santiago
  timezone:
    name: America/Santiago

- name: Instalar Unattended Upgrades, Agente Zabbix2, Net Tools, Tmux, Neofetch, Tree
  apt:
   name:
    - unattended-upgrades
    - zabbix-agent2
    - net-tools
    - tmux
    - neofetch
    - tree
   state: latest
   update_cache: yes

- name: Copiar archivo de configuración agente Zabbix
  copy:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644

- name: Inicia y habilita el agente Zabbix
  service:
    name: zabbix-agent2
    state: started
    enabled: yes

- name: Copiar archivo de configuración SSH
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Reinicia servicio SSH
  service:
    name: sshd
    state: restarted
